# -*- coding: utf-8 -*-
"""Airbnb-Data-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl5lrFDXiL2wGnaQmhD3jNVjDxp7eFOW
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/drive/MyDrive/Data/Airbnb_Open_Data.csv')

df.head()

df.info()

df.columns

df.isnull().sum()

from os import error
df['last review']=pd.to_datetime(df['last review'],errors='coerce')

df['reviews per month']=df['reviews per month'].fillna(0)

df['last review']=df['last review'].fillna(df['last review'].min())

df['lat']=df['lat'].fillna(df['lat'].mean()).astype(float)

df['long']=df['long'].fillna(df['long'].mean()).astype(float)

#df.fillna({'reviews per month':0,'last review':df['last review'].min()},inplace=True)

df.drop(columns=['house_rules','license'],inplace=True)

df.dropna(subset=['NAME','host name','host_identity_verified','neighbourhood group','neighbourhood','country','country code'],inplace=True)

df['price']=df['price'].replace('[\$,]','',regex=True).astype(float)

df['service fee']=df['service fee'].replace('[\$,]','',regex=True).astype(float)

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.isnull().sum()

"""Distribution of listing Price"""

plt.figure(figsize=(10,6))
sns.histplot(df['price'],bins=50,color='red',kde=True)
plt.title('Distribution of listing Price')
plt.xlabel('Price $')
plt.ylabel('Frequency')
plt.show()

"""How are different room size distributed?"""

plt.figure(figsize=(8,5))
sns.countplot(x='room type',data=df,color='blue')
plt.title('Room Type Distributed')
plt.xlabel('Room Type')
plt.ylabel('Count')
plt.show()

"""How are listings distributed across different neighbourhood"""

plt.figure(figsize=(8,5))
sns.countplot(y='neighbourhood group',data=df,color='lightgreen',order=df['neighbourhood group'].value_counts().index)
plt.title('Number of listings by Neighbourhood Group')
plt.xlabel('Count')
plt.ylabel('Neighbourhood Group')
plt.show()

"""What is the relationship between price and room type?"""

plt.figure(figsize=(8,5))
sns.boxplot(x='room type',y='price',hue='room type',data=df,palette='hot')
plt.title('Room Type vs. Price')
plt.xlabel('Room Type')
plt.ylabel('Price')
plt.show

"""How has the number of reviews change over time?"""

plt.figure(figsize=(12, 6))
df.groupby('last review')['number of reviews'].sum().plot(kind='line', color='purple')
plt.title('Total Number of Reviews Over Time')
plt.xlabel('Date of Last Review')
plt.ylabel('Total Number of Reviews')
plt.show()

