# -*- coding: utf-8 -*-
"""Uber-Data-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a50hywuYkU7-mx_eMLGu5eSj0Hbx-R4S
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/Data/UberDataset.csv')

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

df['PURPOSE']=df['PURPOSE'].fillna('NOT')

df['START_DATE']=pd.to_datetime(df['START_DATE'],errors='coerce')

df['END_DATE']=pd.to_datetime(df['END_DATE'],errors='coerce')

df['DATE']=pd.DatetimeIndex(df['START_DATE']).date

df['DATE']=pd.to_datetime(df['DATE'],errors='coerce')

df['TIME']=pd.DatetimeIndex(df['START_DATE']).hour

df['Day-Night']=pd.cut(x=df['TIME'],bins=[0,10,15,19,24],labels=['Morning','Afternoon','Evening','Night'])

df.dropna(inplace=True)

plt.figure(figsize=(20,5))
plt.subplot(1,2,1)

sns.countplot(df['CATEGORY'])

plt.subplot(1,2,2)
sns.countplot(df['PURPOSE'])

plt.figure(figsize=(15,5))

sns.countplot(y='TIME',data=df)

plt.figure(figsize=(15,5))

sns.countplot(y='Day-Night',data=df)

df['MONTH']=pd.DatetimeIndex(df['START_DATE']).month

plt.figure(figsize=(15,6))
sns.countplot(y=df['MONTH'])

